<?php

use Illuminate\Database\Seeder;

class AdminMenuTableSeeder extends Seeder
{
  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {
    \DB::table('admin_menu')->delete();

    \DB::table('admin_menu')->insert([
      0 => [
        'id' => 1,
        'parent_id' => 0,
        'order' => 1,
        'title' => 'Dashboard',
        'icon' => 'fa-bar-chart',
        'uri' => '/',
        'permission' => null,
        'created_at' => null,
        'updated_at' => null,
      ],
      1 => [
        'id' => 2,
        'parent_id' => 0,
        'order' => 9,
        'title' => 'Admin',
        'icon' => 'fa-tasks',
        'uri' => '',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      2 => [
        'id' => 3,
        'parent_id' => 2,
        'order' => 6,
        'title' => 'Users',
        'icon' => 'fa-users',
        'uri' => 'auth/users',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      3 => [
        'id' => 4,
        'parent_id' => 2,
        'order' => 7,
        'title' => 'Roles',
        'icon' => 'fa-user',
        'uri' => 'auth/roles',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      4 => [
        'id' => 5,
        'parent_id' => 2,
        'order' => 8,
        'title' => 'Permission',
        'icon' => 'fa-ban',
        'uri' => 'auth/permissions',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      5 => [
        'id' => 6,
        'parent_id' => 2,
        'order' => 9,
        'title' => 'Menu',
        'icon' => 'fa-bars',
        'uri' => 'auth/menu',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      6 => [
        'id' => 7,
        'parent_id' => 2,
        'order' => 10,
        'title' => 'Operation log',
        'icon' => 'fa-history',
        'uri' => 'auth/logs',
        'permission' => null,
        'created_at' => null,
        'updated_at' => '2020-03-20 15:45:16',
      ],
      7 => [
        'id' => 8,
        'parent_id' => 0,
        'order' => 2,
        'title' => 'Gestion des contenus',
        'icon' => 'fa-book',
        'uri' => 'posts',
        'permission' => '*',
        'created_at' => '2020-03-20 15:44:10',
        'updated_at' => '2020-03-20 15:45:16',
      ],
      8 => [
        'id' => 9,
        'parent_id' => 0,
        'order' => 3,
        'title' => 'Gestion des alertes',
        'icon' => 'fa-bell-o',
        'uri' => 'alerts',
        'permission' => '*',
        'created_at' => '2020-03-20 15:44:39',
        'updated_at' => '2020-03-20 15:45:30',
      ],
      9 => [
        'id' => 10,
        'parent_id' => 0,
        'order' => 7,
        'title' => 'Gestion des catégories',
        'icon' => 'fa-newspaper-o',
        'uri' => 'categories',
        'permission' => '*',
        'created_at' => '2020-03-20 15:45:03',
        'updated_at' => '2020-03-20 15:45:16',
      ],
      10 => [
        'id' => 11,
        'parent_id' => 0,
        'order' => 8,
        'title' => 'Gestion des provinces',
        'icon' => 'fa-map',
        'uri' => 'provinces',
        'permission' => '*',
        'created_at' => '2020-03-23 13:12:01',
        'updated_at' => '2020-03-23 13:41:28',
      ],
      11 => [
        'id' => 12,
        'parent_id' => 0,
        'order' => 4,
        'title' => 'Gestion des diffusions',
        'icon' => 'fa-envelope-o',
        'uri' => 'sms-diffusions',
        'permission' => '*',
        'created_at' => '2020-03-23 13:12:41',
        'updated_at' => '2020-03-23 13:12:41',
      ],
      11 => [
        'id' => 13,
        'parent_id' => 0,
        'order' => 5,
        'title' => 'Suivi de cas',
        'icon' => 'fa-bar-chart',
        'uri' => 'pandemic-stats',
        'permission' => '*',
        'created_at' => '2020-03-23 13:12:41',
        'updated_at' => '2020-03-23 13:12:41',
      ],
      [
        'id' => 14,
        'parent_id' => 0,
        'order' => 6,
        'title' => 'Gestion des diffuesions sms',
        'icon' => 'fa-bars',
        'uri' => 'sms-diffusions',
        'permission' => '*',
        'created_at' => '2020-03-23 13:12:41',
        'updated_at' => '2020-03-23 13:12:41',
      ],
      [
        'id' => 15,
        'parent_id' => 0,
        'order' => 6,
        'title' => 'Suivi de diagnostique',
        'icon' => 'fa-bar-chart',
        'uri' => 'diagnostics',
        'permission' => '*',
        'created_at' => '2020-03-23 13:12:41',
        'updated_at' => '2020-03-23 13:12:41',
      ],
    ]);
  }
}
