<?php

use Illuminate\Database\Seeder;

class FluxHotSpotsTableSeeder extends Seeder
{
  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {
    \DB::table('flux_hot_spots')->delete();

    \DB::table('flux_hot_spots')->insert([
      0 => [
        'id' => 1,
        'name' => 'Inconnue',
        'created_at' => null,
        'updated_at' => null,
      ],
      1 => [
        'id' => 2,
        'name' => 'UPN Djelo',
        'created_at' => null,
        'updated_at' => null,
      ],
      2 => [
        'id' => 3,
        'name' => 'DGC barre',
        'created_at' => null,
        'updated_at' => null,
      ],
      3 => [
        'id' => 4,
        'name' => 'Wenze Muselu/Gambela',
        'created_at' => null,
        'updated_at' => null,
      ],
      4 => [
        'id' => 5,
        'name' => 'Huillerie',
        'created_at' => null,
        'updated_at' => null,
      ],
      5 => [
        'id' => 6,
        'name' => 'Mosqué Centrale Usoke',
        'created_at' => null,
        'updated_at' => null,
      ],
      6 => [
        'id' => 7,
        'name' => 'Arret Centre hospitalier de Kintambo',
        'created_at' => null,
        'updated_at' => null,
      ],
      7 => [
        'id' => 8,
        'name' => 'Arret Stade Velodrome',
        'created_at' => null,
        'updated_at' => null,
      ],
      8 => [
        'id' => 9,
        'name' => 'Cimetiere Kintambo',
        'created_at' => null,
        'updated_at' => null,
      ],
      9 => [
        'id' => 10,
        'name' => 'Arret Bakayaou',
        'created_at' => null,
        'updated_at' => null,
      ],
      10 => [
        'id' => 11,
        'name' => 'Croissement Kianza et Universite',
        'created_at' => null,
        'updated_at' => null,
      ],
      11 => [
        'id' => 12,
        'name' => 'CE TRINITE',
        'created_at' => null,
        'updated_at' => null,
      ],
      12 => [
        'id' => 13,
        'name' => 'Place Commercial de limete(7e rue)',
        'created_at' => null,
        'updated_at' => null,
      ],
      13 => [
        'id' => 14,
        'name' => 'Kinkole', // false
        'created_at' => null,
        'updated_at' => null,
      ],
      14 => [
        'id' => 15,
        'name' => 'INBTP',
        'created_at' => null,
        'updated_at' => null,
      ],
      15 => [
        'id' => 16,
        'name' => 'Parc Mont Ngaliema',
        'created_at' => null,
        'updated_at' => null,
      ],
      16 => [
        'id' => 17,
        'name' => 'Arret Station Macampagne (ML)',
        'created_at' => null,
        'updated_at' => null,
      ],
      17 => [
        'id' => 18,
        'name' => 'Le cerlce gourmand',
        'created_at' => null,
        'updated_at' => null,
      ],
      18 => [
        'id' => 19,
        'name' => 'Ministere des affaires etrangeres',
        'created_at' => null,
        'updated_at' => null,
      ],
      19 => [
        'id' => 20,
        'name' => 'Benseke Nouvelle Cite',
        'created_at' => null,
        'updated_at' => null,
      ],
      20 => [
        'id' => 21,
        'name' => 'Cimetiere sans fil',
        'created_at' => null,
        'updated_at' => null,
      ],
      21 => [
        'id' => 22,
        'name' => 'Food Market Macampagne',
        'created_at' => null,
        'updated_at' => null,
      ],
      22 => [
        'id' => 23,
        'name' => 'Eglise Saint Paul',
        'created_at' => null,
        'updated_at' => null,
      ],
      23 => [
        'id' => 24,
        'name' => 'Hopital general de Kintambo',
        'created_at' => null,
        'updated_at' => null,
      ],
      24 => [
        'id' => 25,
        'name' => 'Salle de fete de la Rotonde Binza',
        'created_at' => null,
        'updated_at' => null,
      ],
      25 => [
        'id' => 26,
        'name' => 'TASOK',
        'created_at' => null,
        'updated_at' => null,
      ],
      26 => [
        'id' => 27,
        'name' => 'Eglise locale Cbfc Itaga',
        'created_at' => null,
        'updated_at' => null,
      ],
      27 => [
        'id' => 28,
        'name' => 'Marché central',
        'created_at' => null,
        'updated_at' => null,
      ],
      28 => [
        'id' => 29,
        'name' => 'Baruti Tabernacle',
        'created_at' => null,
        'updated_at' => null,
      ],
      29 => [
        'id' => 30,
        'name' => 'eglise protestante de lemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      30 => [
        'id' => 31,
        'name' => 'Binza Arret Maternite',
        'created_at' => null,
        'updated_at' => null,
      ],
      31 => [
        'id' => 32,
        'name' => 'Marché Delvaux',
        'created_at' => null,
        'updated_at' => null,
      ],
      32 => [
        'id' => 33,
        'name' => 'Peloustore KIVU',
        'created_at' => null,
        'updated_at' => null,
      ],
      33 => [
        'id' => 34,
        'name' => 'Centre d\'Evangelisation Peniel CEPE',
        'created_at' => null,
        'updated_at' => null,
      ],
      34 => [
        'id' => 35,
        'name' => 'Ejcev Nouvelle Alliance Bima',
        'created_at' => null,
        'updated_at' => null,
      ],
      35 => [
        'id' => 36,
        'name' => 'Paroisse saint François-Xavier',
        'created_at' => null,
        'updated_at' => null,
      ],
      36 => [
        'id' => 37,
        'name' => 'Eglise Catholique Divin Maître',
        'created_at' => null,
        'updated_at' => null,
      ],
      37 => [
        'id' => 38,
        'name' => 'Kinsuka',
        'created_at' => null,
        'updated_at' => null,
      ],
      38 => [
        'id' => 39,
        'name' => 'Matadi Kibala',
        'created_at' => null,
        'updated_at' => null,
      ],
      39 => [
        'id' => 40,
        'name' => 'Arret moulard',
        'created_at' => null,
        'updated_at' => null,
      ],
      40 => [
        'id' => 41,
        'name' => 'Marché BAYAKA',
        'created_at' => null,
        'updated_at' => null,
      ],
      41 => [
        'id' => 42,
        'name' => 'ECC/CEC/BUMBU',
        'created_at' => null,
        'updated_at' => null,
      ],
      42 => [
        'id' => 43,
        'name' => 'Marché selembao',
        'created_at' => null,
        'updated_at' => null,
      ],
      43 => [
        'id' => 44,
        'name' => 'INA et ORCA',
        'created_at' => null,
        'updated_at' => null,
      ],
      44 => [
        'id' => 45,
        'name' => 'Rond Point Ngaba',
        'created_at' => null,
        'updated_at' => null,
      ],
      45 => [
        'id' => 46,
        'name' => 'Marché de Mbanza Lemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      46 => [
        'id' => 47,
        'name' => 'Pont Matete',
        'created_at' => null,
        'updated_at' => null,
      ],
      47 => [
        'id' => 48,
        'name' => 'Place sainte therese',
        'created_at' => null,
        'updated_at' => null,
      ],
      48 => [
        'id' => 49,
        'name' => 'Marché de la Liberté',
        'created_at' => null,
        'updated_at' => null,
      ],
      49 => [
        'id' => 50,
        'name' => 'Marché Mangobo',
        'created_at' => null,
        'updated_at' => null,
      ],
      50 => [
        'id' => 51,
        'name' => 'Rond Point Forescom',
        'created_at' => null,
        'updated_at' => null,
      ],
      51 => [
        'id' => 52, // false
        'name' => 'Marché Mbika',
        'created_at' => null,
        'updated_at' => null,
      ],
      52 => [
        'id' => 53,
        'name' => 'Eglise Kimbanguiste',
        'created_at' => null,
        'updated_at' => null,
      ],
      53 => [
        'id' => 54,
        'name' => 'Place de la gare centrale',
        'created_at' => null,
        'updated_at' => null,
      ],
      54 => [
        'id' => 55, //false
        'name' => 'Eglise Francophone Ecole de Tyrannus',
        'created_at' => null,
        'updated_at' => null,
      ],
      55 => [
        'id' => 56,
        'name' => 'Cimetiere Kimbanseke',
        'created_at' => null,
        'updated_at' => null,
      ],
      56 => [
        'id' => 57,
        'name' => 'Quartier 1 (croissement Boulevard Lumumba)',
        'created_at' => null,
        'updated_at' => null,
      ],
      57 => [
        'id' => 58,
        'name' => 'Mosqué Bon Marche',
        'created_at' => null,
        'updated_at' => null,
      ],
      58 => [
        'id' => 59,
        'name' => 'SONAS',
        'created_at' => null,
        'updated_at' => null,
      ],
      59 => [
        'id' => 60,
        'name' => 'ROND POINT SAFRICAS',
        'created_at' => null,
        'updated_at' => null,
      ],
      60 => [
        'id' => 61,
        'name' => 'Carrigres',
        'created_at' => null,
        'updated_at' => null,
      ],
      61 => [
        'id' => 62,
        'name' => 'le pain de vie',
        'created_at' => null,
        'updated_at' => null,
      ],
      62 => [
        'id' => 63,
        'name' => 'Ministere combat spirituel',
        'created_at' => null,
        'updated_at' => null,
      ],
      63 => [
        'id' => 64,
        'name' => 'Lemba Terminus',
        'created_at' => null,
        'updated_at' => null,
      ],
      64 => [
        'id' => 65,
        'name' => 'Paroisse Saint Eloi',
        'created_at' => null,
        'updated_at' => null,
      ],
      65 => [
        'id' => 66,
        'name' => 'Gabriella',
        'created_at' => null,
        'updated_at' => null,
      ],
      66 => [
        'id' => 67,
        'name' => 'Paroisse Notre-Dame d\'Afrique',
        'created_at' => null,
        'updated_at' => null,
      ],
      67 => [
        'id' => 68,
        'name' => 'Marché Matete',
        'created_at' => null,
        'updated_at' => null,
      ],
      68 => [
        'id' => 69,
        'name' => 'Cimetiere Ndjili Brasserie',
        'created_at' => null,
        'updated_at' => null,
      ],
      69 => [
        'id' => 70,
        'name' => 'ONATRA',
        'created_at' => null,
        'updated_at' => null,
      ],
      70 => [
        'id' => 71,
        'name' => 'Hopital Biamba Marie Mutombo',
        'created_at' => null,
        'updated_at' => null,
      ],
      71 => [
        'id' => 72,
        'name' => 'Eglise des assemblées de dieu',
        'created_at' => null,
        'updated_at' => null,
      ],
      72 => [
        'id' => 73,
        'name' => 'Hotel Sultani',
        'created_at' => null,
        'updated_at' => null,
      ],
      73 => [
        'id' => 74,
        'name' => 'Maché De Kadi',
        'created_at' => null,
        'updated_at' => null,
      ],
      74 => [
        'id' => 75,
        'name' => 'Avenue du Commerce et Kasa vubu',
        'created_at' => null,
        'updated_at' => null,
      ],
      75 => [
        'id' => 76,
        'name' => 'Centre Evangelique Emmanuel Langa-langa',
        'created_at' => null,
        'updated_at' => null,
      ],
      76 => [
        'id' => 77,
        'name' => 'Mbudi Nature',
        'created_at' => null,
        'updated_at' => null,
      ],
      77 => [
        'id' => 78,
        'name' => 'ASSANEF',
        'created_at' => null,
        'updated_at' => null,
      ],
      78 => [
        'id' => 79,
        'name' => 'Shark Club',
        'created_at' => null,
        'updated_at' => null,
      ],
      79 => [
        'id' => 80,
        'name' => 'Arret Socimat',
        'created_at' => null,
        'updated_at' => null,
      ],
      80 => [
        'id' => 81,
        'name' => 'BATETELA',
        'created_at' => null,
        'updated_at' => null,
      ],
      81 => [
        'id' => 82,
        'name' => 'Immeuble CNSS',
        'created_at' => null,
        'updated_at' => null,
      ],
      82 => [
        'id' => 83,
        'name' => 'Eglise Notre Dame de Fatima',
        'created_at' => null,
        'updated_at' => null,
      ],
      83 => [
        'id' => 84,
        'name' => 'FIKIN',
        'created_at' => null,
        'updated_at' => null,
      ],
      84 => [
        'id' => 85,
        'name' => 'O\'Poeta',
        'created_at' => null,
        'updated_at' => null,
      ],
      85 => [
        'id' => 86,
        'name' => 'La voix du fleuve',
        'created_at' => null,
        'updated_at' => null,
      ],
      86 => [
        'id' => 87,
        'name' => 'Poste',
        'created_at' => null,
        'updated_at' => null,
      ],
      87 => [
        'id' => 88,
        'name' => 'Mosqué Kingabwa',
        'created_at' => null,
        'updated_at' => null,
      ],
      88 => [
        'id' => 89,
        'name' => 'Hotel Memling',
        'created_at' => null,
        'updated_at' => null,
      ],
      89 => [
        'id' => 90,
        'name' => 'Arret Station Centre Superieur',
        'created_at' => null,
        'updated_at' => null,
      ],
      90 => [
        'id' => 91,
        'name' => 'Hotel du Fleuve',
        'created_at' => null,
        'updated_at' => null,
      ],
      91 => [
        'id' => 92,
        'name' => 'Shoprite',
        'created_at' => null,
        'updated_at' => null,
      ],
      92 => [
        'id' => 93,
        'name' => 'Immeuble Cosmos',
        'created_at' => null,
        'updated_at' => null,
      ],
      93 => [
        'id' => 94,
        'name' => 'Necropole entre ciel et terre',
        'created_at' => null,
        'updated_at' => null,
      ],
      94 => [
        'id' => 95,
        'name' => 'Cimetiere Mingadi',
        'created_at' => null,
        'updated_at' => null,
      ],
      95 => [
        'id' => 96,
        'name' => 'Mimoza plaza',
        'created_at' => null,
        'updated_at' => null,
      ],
      96 => [
        'id' => 97,
        'name' => 'Hall de la Gombe',
        'created_at' => null,
        'updated_at' => null,
      ],
      97 => [
        'id' => 98,
        'name' => 'Le premier Shopping Mall',
        'created_at' => null,
        'updated_at' => null,
      ],
      98 => [
        'id' => 99,
        'name' => 'Paroisse Sacre Coeur',
        'created_at' => null,
        'updated_at' => null,
      ],
      99 => [
        'id' => 100,
        'name' => 'HOTEL DU GOUVERNEMENT',
        'created_at' => null,
        'updated_at' => null,
      ],
      100 => [
        'id' => 101,
        'name' => 'Dvin',
        'created_at' => null,
        'updated_at' => null,
      ],
      101 => [
        'id' => 102, //false
        'name' => 'Aéroport Ndolo',
        'created_at' => null,
        'updated_at' => null,
      ],
      102 => [
        'id' => 103,
        'name' => 'Aéroport Ndjili',
        'created_at' => null,
        'updated_at' => null,
      ],
    ]);
  }
}
