<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FluxZonesTableSeeder extends Seeder
{
  /**
   * Auto generated seed file
   *
   * @return void
   */
  public function run()
  {
    DB::table('flux_zones')->truncate();
    DB::table('flux_zones')->insert([
      0 => [
        'id' => 1,
        'name' => 'Aba',
        'created_at' => null,
        'updated_at' => null,
      ],
      1 => [
        'id' => 2,
        'name' => 'Adi',
        'created_at' => null,
        'updated_at' => null,
      ],
      2 => [
        'id' => 3,
        'name' => 'Alimbongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      3 => [
        'id' => 4,
        'name' => 'Angumu',
        'created_at' => null,
        'updated_at' => null,
      ],
      4 => [
        'id' => 5,
        'name' => 'Ankoro',
        'created_at' => null,
        'updated_at' => null,
      ],
      5 => [
        'id' => 6,
        'name' => 'Ariwara',
        'created_at' => null,
        'updated_at' => null,
      ],
      6 => [
        'id' => 7,
        'name' => 'Bafwasende',
        'created_at' => null,
        'updated_at' => null,
      ],
      7 => [
        'id' => 8,
        'name' => 'Baka',
        'created_at' => null,
        'updated_at' => null,
      ],
      8 => [
        'id' => 9,
        'name' => 'Banalia',
        'created_at' => null,
        'updated_at' => null,
      ],
      9 => [
        'id' => 10,
        'name' => 'Barumbu',
        'created_at' => null,
        'updated_at' => null,
      ],
      10 => [
        'id' => 11,
        'name' => 'Basoko',
        'created_at' => null,
        'updated_at' => null,
      ],
      11 => [
        'id' => 12,
        'name' => 'Bena Leka',
        'created_at' => null,
        'updated_at' => null,
      ],
      12 => [
        'id' => 13,
        'name' => 'Bena Tshiadi',
        'created_at' => null,
        'updated_at' => null,
      ],
      13 => [
        'id' => 14,
        'name' => 'Bengamisa',
        'created_at' => null,
        'updated_at' => null,
      ],
      14 => [
        'id' => 15,
        'name' => 'Beni',
        'created_at' => null,
        'updated_at' => null,
      ],
      15 => [
        'id' => 16,
        'name' => 'Bibanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      16 => [
        'id' => 17,
        'name' => 'Biena',
        'created_at' => null,
        'updated_at' => null,
      ],
      17 => [
        'id' => 18,
        'name' => 'Bikoro',
        'created_at' => null,
        'updated_at' => null,
      ],
      18 => [
        'id' => 19,
        'name' => 'Bilomba',
        'created_at' => null,
        'updated_at' => null,
      ],
      19 => [
        'id' => 20,
        'name' => 'Binga',
        'created_at' => null,
        'updated_at' => null,
      ],
      20 => [
        'id' => 21,
        'name' => 'Binza',
        'created_at' => null,
        'updated_at' => null,
      ],
      21 => [
        'id' => 22,
        'name' => 'Binza Meteo',
        'created_at' => null,
        'updated_at' => null,
      ],
      22 => [
        'id' => 23,
        'name' => 'Binza Ozone',
        'created_at' => null,
        'updated_at' => null,
      ],
      23 => [
        'id' => 24,
        'name' => 'Birambizo',
        'created_at' => null,
        'updated_at' => null,
      ],
      24 => [
        'id' => 25,
        'name' => 'Boko',
        'created_at' => null,
        'updated_at' => null,
      ],
      25 => [
        'id' => 26,
        'name' => 'Boko-Kivulu',
        'created_at' => null,
        'updated_at' => null,
      ],
      26 => [
        'id' => 27,
        'name' => 'Bokoro',
        'created_at' => null,
        'updated_at' => null,
      ],
      27 => [
        'id' => 28,
        'name' => 'Bolobo',
        'created_at' => null,
        'updated_at' => null,
      ],
      28 => [
        'id' => 29,
        'name' => 'Bolomba',
        'created_at' => null,
        'updated_at' => null,
      ],
      29 => [
        'id' => 30,
        'name' => 'Boma',
        'created_at' => null,
        'updated_at' => null,
      ],
      30 => [
        'id' => 31,
        'name' => 'Boma Bungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      31 => [
        'id' => 32,
        'name' => 'Bominenge',
        'created_at' => null,
        'updated_at' => null,
      ],
      32 => [
        'id' => 33,
        'name' => 'Bosondjo',
        'created_at' => null,
        'updated_at' => null,
      ],
      33 => [
        'id' => 34,
        'name' => 'Bukama',
        'created_at' => null,
        'updated_at' => null,
      ],
      34 => [
        'id' => 35,
        'name' => 'Bulungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      35 => [
        'id' => 36,
        'name' => 'Bumba',
        'created_at' => null,
        'updated_at' => null,
      ],
      36 => [
        'id' => 37,
        'name' => 'Bumbu',
        'created_at' => null,
        'updated_at' => null,
      ],
      37 => [
        'id' => 38,
        'name' => 'Bunia',
        'created_at' => null,
        'updated_at' => null,
      ],
      38 => [
        'id' => 39,
        'name' => 'Bunkeya',
        'created_at' => null,
        'updated_at' => null,
      ],
      39 => [
        'id' => 40,
        'name' => 'Bunkonde',
        'created_at' => null,
        'updated_at' => null,
      ],
      40 => [
        'id' => 41,
        'name' => 'Bunyakiri',
        'created_at' => null,
        'updated_at' => null,
      ],
      41 => [
        'id' => 42,
        'name' => 'Businga',
        'created_at' => null,
        'updated_at' => null,
      ],
      42 => [
        'id' => 43,
        'name' => 'Buta',
        'created_at' => null,
        'updated_at' => null,
      ],
      43 => [
        'id' => 44,
        'name' => 'Cilundu',
        'created_at' => null,
        'updated_at' => null,
      ],
      44 => [
        'id' => 45,
        'name' => 'Demba',
        'created_at' => null,
        'updated_at' => null,
      ],
      45 => [
        'id' => 46,
        'name' => 'Dibaya',
        'created_at' => null,
        'updated_at' => null,
      ],
      46 => [
        'id' => 47,
        'name' => 'Dilala',
        'created_at' => null,
        'updated_at' => null,
      ],
      47 => [
        'id' => 48,
        'name' => 'Dilolo',
        'created_at' => null,
        'updated_at' => null,
      ],
      48 => [
        'id' => 49,
        'name' => 'Diulu',
        'created_at' => null,
        'updated_at' => null,
      ],
      49 => [
        'id' => 50,
        'name' => 'Djalo Djeka',
        'created_at' => null,
        'updated_at' => null,
      ],
      50 => [
        'id' => 51,
        'name' => 'Djuma',
        'created_at' => null,
        'updated_at' => null,
      ],
      51 => [
        'id' => 52,
        'name' => 'Drodro',
        'created_at' => null,
        'updated_at' => null,
      ],
      52 => [
        'id' => 53,
        'name' => 'Fizi',
        'created_at' => null,
        'updated_at' => null,
      ],
      53 => [
        'id' => 54,
        'name' => 'Fungurume',
        'created_at' => null,
        'updated_at' => null,
      ],
      54 => [
        'id' => 55,
        'name' => 'Gbadolite',
        'created_at' => null,
        'updated_at' => null,
      ],
      55 => [
        'id' => 56,
        'name' => 'Gemena',
        'created_at' => null,
        'updated_at' => null,
      ],
      56 => [
        'id' => 57,
        'name' => 'Gethy',
        'created_at' => null,
        'updated_at' => null,
      ],
      57 => [
        'id' => 58,
        'name' => 'Gombari',
        'created_at' => null,
        'updated_at' => null,
      ],
      58 => [
        'id' => 59,
        'name' => 'Gombe',
        'created_at' => null,
        'updated_at' => null,
      ],
      59 => [
        'id' => 60,
        'name' => 'Hauts-Plateaux',
        'created_at' => null,
        'updated_at' => null,
      ],
      60 => [
        'id' => 61,
        'name' => 'Hors_Zone',
        'created_at' => null,
        'updated_at' => null,
      ],
      61 => [
        'id' => 62,
        'name' => 'Ibanda',
        'created_at' => null,
        'updated_at' => null,
      ],
      62 => [
        'id' => 63,
        'name' => 'Idiofa',
        'created_at' => null,
        'updated_at' => null,
      ],
      63 => [
        'id' => 64,
        'name' => 'Idjwi',
        'created_at' => null,
        'updated_at' => null,
      ],
      64 => [
        'id' => 65,
        'name' => 'Ilebo',
        'created_at' => null,
        'updated_at' => null,
      ],
      65 => [
        'id' => 66,
        'name' => 'Inga',
        'created_at' => null,
        'updated_at' => null,
      ],
      66 => [
        'id' => 67,
        'name' => 'Isangi',
        'created_at' => null,
        'updated_at' => null,
      ],
      67 => [
        'id' => 68,
        'name' => 'Isiro',
        'created_at' => null,
        'updated_at' => null,
      ],
      68 => [
        'id' => 69,
        'name' => 'Itebero',
        'created_at' => null,
        'updated_at' => null,
      ],
      69 => [
        'id' => 70,
        'name' => 'Itombwe',
        'created_at' => null,
        'updated_at' => null,
      ],
      70 => [
        'id' => 71,
        'name' => 'Kabambare',
        'created_at' => null,
        'updated_at' => null,
      ],
      71 => [
        'id' => 72,
        'name' => 'Kabare',
        'created_at' => null,
        'updated_at' => null,
      ],
      72 => [
        'id' => 73,
        'name' => 'Kabeya Kamuanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      73 => [
        'id' => 74,
        'name' => 'Kabinda',
        'created_at' => null,
        'updated_at' => null,
      ],
      74 => [
        'id' => 75,
        'name' => 'Kabondo',
        'created_at' => null,
        'updated_at' => null,
      ],
      75 => [
        'id' => 76,
        'name' => 'Kabondo Dianda',
        'created_at' => null,
        'updated_at' => null,
      ],
      76 => [
        'id' => 77,
        'name' => 'Kabongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      77 => [
        'id' => 78,
        'name' => 'Kahemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      78 => [
        'id' => 79,
        'name' => 'Kalamba',
        'created_at' => null,
        'updated_at' => null,
      ],
      79 => [
        'id' => 80,
        'name' => 'Kalamu I',
        'created_at' => null,
        'updated_at' => null,
      ],
      80 => [
        'id' => 81,
        'name' => 'Kalamu II',
        'created_at' => null,
        'updated_at' => null,
      ],
      81 => [
        'id' => 82,
        'name' => 'Kalemie',
        'created_at' => null,
        'updated_at' => null,
      ],
      82 => [
        'id' => 83,
        'name' => 'Kalenda',
        'created_at' => null,
        'updated_at' => null,
      ],
      83 => [
        'id' => 84,
        'name' => 'Kalima',
        'created_at' => null,
        'updated_at' => null,
      ],
      84 => [
        'id' => 85,
        'name' => 'Kalole',
        'created_at' => null,
        'updated_at' => null,
      ],
      85 => [
        'id' => 86,
        'name' => 'Kalonda Ouest',
        'created_at' => null,
        'updated_at' => null,
      ],
      86 => [
        'id' => 87,
        'name' => 'Kalonge',
        'created_at' => null,
        'updated_at' => null,
      ],
      87 => [
        'id' => 88,
        'name' => 'Kamango',
        'created_at' => null,
        'updated_at' => null,
      ],
      88 => [
        'id' => 89,
        'name' => 'Kamiji',
        'created_at' => null,
        'updated_at' => null,
      ],
      89 => [
        'id' => 90,
        'name' => 'Kamina',
        'created_at' => null,
        'updated_at' => null,
      ],
      90 => [
        'id' => 91,
        'name' => 'Kamituga',
        'created_at' => null,
        'updated_at' => null,
      ],
      91 => [
        'id' => 92,
        'name' => 'Kamonia',
        'created_at' => null,
        'updated_at' => null,
      ],
      92 => [
        'id' => 93,
        'name' => 'Kampemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      93 => [
        'id' => 94,
        'name' => 'Kampene',
        'created_at' => null,
        'updated_at' => null,
      ],
      94 => [
        'id' => 95,
        'name' => 'Kamwesha',
        'created_at' => null,
        'updated_at' => null,
      ],
      95 => [
        'id' => 96,
        'name' => 'Kananga',
        'created_at' => null,
        'updated_at' => null,
      ],
      96 => [
        'id' => 97,
        'name' => 'Kanda Kanda',
        'created_at' => null,
        'updated_at' => null,
      ],
      97 => [
        'id' => 98,
        'name' => 'Kangu',
        'created_at' => null,
        'updated_at' => null,
      ],
      98 => [
        'id' => 99,
        'name' => 'Kaniama',
        'created_at' => null,
        'updated_at' => null,
      ],
      99 => [
        'id' => 100,
        'name' => 'Kanzenze',
        'created_at' => null,
        'updated_at' => null,
      ],
      100 => [
        'id' => 101,
        'name' => 'Kapolowe',
        'created_at' => null,
        'updated_at' => null,
      ],
      101 => [
        'id' => 102,
        'name' => 'Karawa',
        'created_at' => null,
        'updated_at' => null,
      ],
      102 => [
        'id' => 103,
        'name' => 'Karisimbi',
        'created_at' => null,
        'updated_at' => null,
      ],
      103 => [
        'id' => 104,
        'name' => 'Kasa-Vubu',
        'created_at' => null,
        'updated_at' => null,
      ],
      104 => [
        'id' => 105,
        'name' => 'Kasaji',
        'created_at' => null,
        'updated_at' => null,
      ],
      105 => [
        'id' => 106,
        'name' => 'Kasansa',
        'created_at' => null,
        'updated_at' => null,
      ],
      106 => [
        'id' => 107,
        'name' => 'Kashobwe',
        'created_at' => null,
        'updated_at' => null,
      ],
      107 => [
        'id' => 108,
        'name' => 'Kasongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      108 => [
        'id' => 109,
        'name' => 'Katako Kombe',
        'created_at' => null,
        'updated_at' => null,
      ],
      109 => [
        'id' => 110,
        'name' => 'Katana',
        'created_at' => null,
        'updated_at' => null,
      ],
      110 => [
        'id' => 111,
        'name' => 'Katwa',
        'created_at' => null,
        'updated_at' => null,
      ],
      111 => [
        'id' => 112,
        'name' => 'Kayna',
        'created_at' => null,
        'updated_at' => null,
      ],
      112 => [
        'id' => 113,
        'name' => 'Kenge',
        'created_at' => null,
        'updated_at' => null,
      ],
      113 => [
        'id' => 114,
        'name' => 'Kibirizi',
        'created_at' => null,
        'updated_at' => null,
      ],
      114 => [
        'id' => 115,
        'name' => 'Kibunzi',
        'created_at' => null,
        'updated_at' => null,
      ],
      115 => [
        'id' => 116,
        'name' => 'Kikimi',
        'created_at' => null,
        'updated_at' => null,
      ],
      116 => [
        'id' => 117,
        'name' => 'Kikongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      117 => [
        'id' => 118,
        'name' => 'Kikula',
        'created_at' => null,
        'updated_at' => null,
      ],
      118 => [
        'id' => 119,
        'name' => 'Kikwit-Sud',
        'created_at' => null,
        'updated_at' => null,
      ],
      119 => [
        'id' => 120,
        'name' => 'Kilwa',
        'created_at' => null,
        'updated_at' => null,
      ],
      120 => [
        'id' => 121,
        'name' => 'Kimbanseke',
        'created_at' => null,
        'updated_at' => null,
      ],
      121 => [
        'id' => 122,
        'name' => 'Kimpangu',
        'created_at' => null,
        'updated_at' => null,
      ],
      122 => [
        'id' => 123,
        'name' => 'Kimpese',
        'created_at' => null,
        'updated_at' => null,
      ],
      123 => [
        'id' => 124,
        'name' => 'Kinda',
        'created_at' => null,
        'updated_at' => null,
      ],
      124 => [
        'id' => 125,
        'name' => 'Kindu',
        'created_at' => null,
        'updated_at' => null,
      ],
      125 => [
        'id' => 126,
        'name' => 'Kingabwa',
        'created_at' => null,
        'updated_at' => null,
      ],
      126 => [
        'id' => 127,
        'name' => 'Kinkonzi',
        'created_at' => null,
        'updated_at' => null,
      ],
      127 => [
        'id' => 128,
        'name' => 'Kinshasa',
        'created_at' => null,
        'updated_at' => null,
      ],
      128 => [
        'id' => 129,
        'name' => 'Kintambo',
        'created_at' => null,
        'updated_at' => null,
      ],
      129 => [
        'id' => 130,
        'name' => 'Kipushi',
        'created_at' => null,
        'updated_at' => null,
      ],
      130 => [
        'id' => 131,
        'name' => 'Kirotshe',
        'created_at' => null,
        'updated_at' => null,
      ],
      131 => [
        'id' => 132,
        'name' => 'Kisantu',
        'created_at' => null,
        'updated_at' => null,
      ],
      132 => [
        'id' => 133,
        'name' => 'Kisenso',
        'created_at' => null,
        'updated_at' => null,
      ],
      133 => [
        'id' => 134,
        'name' => 'Kitangwa',
        'created_at' => null,
        'updated_at' => null,
      ],
      134 => [
        'id' => 135,
        'name' => 'Kitenda',
        'created_at' => null,
        'updated_at' => null,
      ],
      135 => [
        'id' => 136,
        'name' => 'Kitenge',
        'created_at' => null,
        'updated_at' => null,
      ],
      136 => [
        'id' => 137,
        'name' => 'Kitona',
        'created_at' => null,
        'updated_at' => null,
      ],
      137 => [
        'id' => 138,
        'name' => 'Kokolo',
        'created_at' => null,
        'updated_at' => null,
      ],
      138 => [
        'id' => 139,
        'name' => 'Kole',
        'created_at' => null,
        'updated_at' => null,
      ],
      139 => [
        'id' => 140,
        'name' => 'Komanda',
        'created_at' => null,
        'updated_at' => null,
      ],
      140 => [
        'id' => 141,
        'name' => 'Kuimba',
        'created_at' => null,
        'updated_at' => null,
      ],
      141 => [
        'id' => 142,
        'name' => 'Kwilu-Ngongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      142 => [
        'id' => 143,
        'name' => 'Kyondo',
        'created_at' => null,
        'updated_at' => null,
      ],
      143 => [
        'id' => 144,
        'name' => 'Lemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      144 => [
        'id' => 145,
        'name' => 'Lemera',
        'created_at' => null,
        'updated_at' => null,
      ],
      145 => [
        'id' => 146,
        'name' => 'Likasi',
        'created_at' => null,
        'updated_at' => null,
      ],
      146 => [
        'id' => 147,
        'name' => 'Limete',
        'created_at' => null,
        'updated_at' => null,
      ],
      147 => [
        'id' => 148,
        'name' => 'Lisala',
        'created_at' => null,
        'updated_at' => null,
      ],
      148 => [
        'id' => 149,
        'name' => 'Lodja',
        'created_at' => null,
        'updated_at' => null,
      ],
      149 => [
        'id' => 150,
        'name' => 'Logo',
        'created_at' => null,
        'updated_at' => null,
      ],
      150 => [
        'id' => 151,
        'name' => 'Loko',
        'created_at' => null,
        'updated_at' => null,
      ],
      151 => [
        'id' => 152,
        'name' => 'Lualaba',
        'created_at' => null,
        'updated_at' => null,
      ],
      152 => [
        'id' => 153,
        'name' => 'Luambo',
        'created_at' => null,
        'updated_at' => null,
      ],
      153 => [
        'id' => 154,
        'name' => 'Lubero',
        'created_at' => null,
        'updated_at' => null,
      ],
      154 => [
        'id' => 155,
        'name' => 'Lubondaie',
        'created_at' => null,
        'updated_at' => null,
      ],
      155 => [
        'id' => 156,
        'name' => 'Lubudi',
        'created_at' => null,
        'updated_at' => null,
      ],
      156 => [
        'id' => 157,
        'name' => 'Lubumbashi',
        'created_at' => null,
        'updated_at' => null,
      ],
      157 => [
        'id' => 158,
        'name' => 'Lubunga',
        'created_at' => null,
        'updated_at' => null,
      ],
      158 => [
        'id' => 159,
        'name' => 'Ludimbi Lukula',
        'created_at' => null,
        'updated_at' => null,
      ],
      159 => [
        'id' => 160,
        'name' => 'Luebo',
        'created_at' => null,
        'updated_at' => null,
      ],
      160 => [
        'id' => 161,
        'name' => 'Luiza',
        'created_at' => null,
        'updated_at' => null,
      ],
      161 => [
        'id' => 162,
        'name' => 'Lukula',
        'created_at' => null,
        'updated_at' => null,
      ],
      162 => [
        'id' => 163,
        'name' => 'Luozi',
        'created_at' => null,
        'updated_at' => null,
      ],
      163 => [
        'id' => 164,
        'name' => 'Luputa',
        'created_at' => null,
        'updated_at' => null,
      ],
      164 => [
        'id' => 165,
        'name' => 'Lusangi',
        'created_at' => null,
        'updated_at' => null,
      ],
      165 => [
        'id' => 166,
        'name' => 'Lwamba',
        'created_at' => null,
        'updated_at' => null,
      ],
      166 => [
        'id' => 167,
        'name' => 'Mahagi',
        'created_at' => null,
        'updated_at' => null,
      ],
      167 => [
        'id' => 168,
        'name' => 'Makala',
        'created_at' => null,
        'updated_at' => null,
      ],
      168 => [
        'id' => 169,
        'name' => 'Makiso-Kisangani',
        'created_at' => null,
        'updated_at' => null,
      ],
      169 => [
        'id' => 170,
        'name' => 'Malemba Nkulu',
        'created_at' => null,
        'updated_at' => null,
      ],
      170 => [
        'id' => 171,
        'name' => 'Maluku I',
        'created_at' => null,
        'updated_at' => null,
      ],
      171 => [
        'id' => 172,
        'name' => 'Mambasa',
        'created_at' => null,
        'updated_at' => null,
      ],
      172 => [
        'id' => 173,
        'name' => 'Mangembo',
        'created_at' => null,
        'updated_at' => null,
      ],
      173 => [
        'id' => 174,
        'name' => 'Manguredjipa',
        'created_at' => null,
        'updated_at' => null,
      ],
      174 => [
        'id' => 175,
        'name' => 'Manika',
        'created_at' => null,
        'updated_at' => null,
      ],
      175 => [
        'id' => 176,
        'name' => 'Masa',
        'created_at' => null,
        'updated_at' => null,
      ],
      176 => [
        'id' => 177,
        'name' => 'Masereka',
        'created_at' => null,
        'updated_at' => null,
      ],
      177 => [
        'id' => 178,
        'name' => 'Masina I',
        'created_at' => null,
        'updated_at' => null,
      ],
      178 => [
        'id' => 179,
        'name' => 'Masina II',
        'created_at' => null,
        'updated_at' => null,
      ],
      179 => [
        'id' => 180,
        'name' => 'Masisi',
        'created_at' => null,
        'updated_at' => null,
      ],
      180 => [
        'id' => 181,
        'name' => 'Masuika',
        'created_at' => null,
        'updated_at' => null,
      ],
      181 => [
        'id' => 182,
        'name' => 'Matadi',
        'created_at' => null,
        'updated_at' => null,
      ],
      182 => [
        'id' => 183,
        'name' => 'Matete',
        'created_at' => null,
        'updated_at' => null,
      ],
      183 => [
        'id' => 184,
        'name' => 'Mbanza-Ngungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      184 => [
        'id' => 185,
        'name' => 'Miabi',
        'created_at' => null,
        'updated_at' => null,
      ],
      185 => [
        'id' => 186,
        'name' => 'Mikalayi',
        'created_at' => null,
        'updated_at' => null,
      ],
      186 => [
        'id' => 187,
        'name' => 'Minembwe',
        'created_at' => null,
        'updated_at' => null,
      ],
      187 => [
        'id' => 188,
        'name' => 'Minova',
        'created_at' => null,
        'updated_at' => null,
      ],
      188 => [
        'id' => 189,
        'name' => 'Moanda',
        'created_at' => null,
        'updated_at' => null,
      ],
      189 => [
        'id' => 190,
        'name' => 'Mokala',
        'created_at' => null,
        'updated_at' => null,
      ],
      190 => [
        'id' => 191,
        'name' => 'Monga',
        'created_at' => null,
        'updated_at' => null,
      ],
      191 => [
        'id' => 192,
        'name' => 'Mongbalu',
        'created_at' => null,
        'updated_at' => null,
      ],
      192 => [
        'id' => 193,
        'name' => 'Mont Ngafula I',
        'created_at' => null,
        'updated_at' => null,
      ],
      193 => [
        'id' => 194,
        'name' => 'Mont Ngafula II',
        'created_at' => null,
        'updated_at' => null,
      ],
      194 => [
        'id' => 195,
        'name' => 'Mukanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      195 => [
        'id' => 196,
        'name' => 'Mukumbi',
        'created_at' => null,
        'updated_at' => null,
      ],
      196 => [
        'id' => 197,
        'name' => 'Mulongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      197 => [
        'id' => 198,
        'name' => 'Mulumba',
        'created_at' => null,
        'updated_at' => null,
      ],
      198 => [
        'id' => 199,
        'name' => 'Mushie',
        'created_at' => null,
        'updated_at' => null,
      ],
      199 => [
        'id' => 200,
        'name' => 'Musienene',
        'created_at' => null,
        'updated_at' => null,
      ],
      200 => [
        'id' => 201,
        'name' => 'Mutena',
        'created_at' => null,
        'updated_at' => null,
      ],
      201 => [
        'id' => 202,
        'name' => 'Mutoto',
        'created_at' => null,
        'updated_at' => null,
      ],
      202 => [
        'id' => 203,
        'name' => 'Mutshatsha',
        'created_at' => null,
        'updated_at' => null,
      ],
      203 => [
        'id' => 204,
        'name' => 'Mutwanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      204 => [
        'id' => 205,
        'name' => 'Mweka',
        'created_at' => null,
        'updated_at' => null,
      ],
      205 => [
        'id' => 206,
        'name' => 'Mwene Ditu',
        'created_at' => null,
        'updated_at' => null,
      ],
      206 => [
        'id' => 207,
        'name' => 'Mwenga',
        'created_at' => null,
        'updated_at' => null,
      ],
      207 => [
        'id' => 208,
        'name' => 'Mweso',
        'created_at' => null,
        'updated_at' => null,
      ],
      208 => [
        'id' => 209,
        'name' => 'Ndage',
        'created_at' => null,
        'updated_at' => null,
      ],
      209 => [
        'id' => 210,
        'name' => 'Ndekesha',
        'created_at' => null,
        'updated_at' => null,
      ],
      210 => [
        'id' => 211,
        'name' => 'Ndjili',
        'created_at' => null,
        'updated_at' => null,
      ],
      211 => [
        'id' => 212,
        'name' => 'Ngandajika',
        'created_at' => null,
        'updated_at' => null,
      ],
      212 => [
        'id' => 213,
        'name' => 'Ngidinga',
        'created_at' => null,
        'updated_at' => null,
      ],
      213 => [
        'id' => 214,
        'name' => 'Ngiri-Ngiri',
        'created_at' => null,
        'updated_at' => null,
      ],
      214 => [
        'id' => 215,
        'name' => 'Nia-Nia',
        'created_at' => null,
        'updated_at' => null,
      ],
      215 => [
        'id' => 216,
        'name' => 'Niangara',
        'created_at' => null,
        'updated_at' => null,
      ],
      216 => [
        'id' => 217,
        'name' => 'Nioki',
        'created_at' => null,
        'updated_at' => null,
      ],
      217 => [
        'id' => 218,
        'name' => 'Nsele',
        'created_at' => null,
        'updated_at' => null,
      ],
      218 => [
        'id' => 219,
        'name' => 'Nsona-Mpangu',
        'created_at' => null,
        'updated_at' => null,
      ],
      219 => [
        'id' => 220,
        'name' => 'Nundu',
        'created_at' => null,
        'updated_at' => null,
      ],
      220 => [
        'id' => 221,
        'name' => 'Nyakunde',
        'created_at' => null,
        'updated_at' => null,
      ],
      221 => [
        'id' => 222,
        'name' => 'Nyangezi',
        'created_at' => null,
        'updated_at' => null,
      ],
      222 => [
        'id' => 223,
        'name' => 'Nyarambe',
        'created_at' => null,
        'updated_at' => null,
      ],
      223 => [
        'id' => 224,
        'name' => 'Nyemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      224 => [
        'id' => 225,
        'name' => 'Nyiragongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      225 => [
        'id' => 226,
        'name' => 'Oicha',
        'created_at' => null,
        'updated_at' => null,
      ],
      226 => [
        'id' => 227,
        'name' => 'Omendjadi',
        'created_at' => null,
        'updated_at' => null,
      ],
      227 => [
        'id' => 228,
        'name' => 'Pimu',
        'created_at' => null,
        'updated_at' => null,
      ],
      228 => [
        'id' => 229,
        'name' => 'Poko',
        'created_at' => null,
        'updated_at' => null,
      ],
      229 => [
        'id' => 230,
        'name' => 'Police',
        'created_at' => null,
        'updated_at' => null,
      ],
      230 => [
        'id' => 231,
        'name' => 'Pweto',
        'created_at' => null,
        'updated_at' => null,
      ],
      231 => [
        'id' => 232,
        'name' => 'Rungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      232 => [
        'id' => 233,
        'name' => 'Rutshuru',
        'created_at' => null,
        'updated_at' => null,
      ],
      233 => [
        'id' => 234,
        'name' => 'Ruzizi',
        'created_at' => null,
        'updated_at' => null,
      ],
      234 => [
        'id' => 235,
        'name' => 'Rwanguba',
        'created_at' => null,
        'updated_at' => null,
      ],
      235 => [
        'id' => 236,
        'name' => 'Rwashi',
        'created_at' => null,
        'updated_at' => null,
      ],
      236 => [
        'id' => 237,
        'name' => 'Sakania',
        'created_at' => null,
        'updated_at' => null,
      ],
      237 => [
        'id' => 238,
        'name' => 'Samba',
        'created_at' => null,
        'updated_at' => null,
      ],
      238 => [
        'id' => 239,
        'name' => 'Sandoa',
        'created_at' => null,
        'updated_at' => null,
      ],
      239 => [
        'id' => 240,
        'name' => 'Saramabila',
        'created_at' => null,
        'updated_at' => null,
      ],
      240 => [
        'id' => 241,
        'name' => 'Seke-Banza',
        'created_at' => null,
        'updated_at' => null,
      ],
      241 => [
        'id' => 242,
        'name' => 'Selembao',
        'created_at' => null,
        'updated_at' => null,
      ],
      242 => [
        'id' => 243,
        'name' => 'Shabunda',
        'created_at' => null,
        'updated_at' => null,
      ],
      243 => [
        'id' => 244,
        'name' => 'Sona-Bata',
        'created_at' => null,
        'updated_at' => null,
      ],
      244 => [
        'id' => 245,
        'name' => 'Tandala',
        'created_at' => null,
        'updated_at' => null,
      ],
      245 => [
        'id' => 246,
        'name' => 'Tembo',
        'created_at' => null,
        'updated_at' => null,
      ],
      246 => [
        'id' => 247,
        'name' => 'Tshamilemba',
        'created_at' => null,
        'updated_at' => null,
      ],
      247 => [
        'id' => 248,
        'name' => 'Tshela',
        'created_at' => null,
        'updated_at' => null,
      ],
      248 => [
        'id' => 249,
        'name' => 'Tshikapa',
        'created_at' => null,
        'updated_at' => null,
      ],
      249 => [
        'id' => 250,
        'name' => 'Tshilenge',
        'created_at' => null,
        'updated_at' => null,
      ],
      250 => [
        'id' => 251,
        'name' => 'Tshishimbi',
        'created_at' => null,
        'updated_at' => null,
      ],
      251 => [
        'id' => 252,
        'name' => 'Ubundu',
        'created_at' => null,
        'updated_at' => null,
      ],
      252 => [
        'id' => 253,
        'name' => 'Uvira',
        'created_at' => null,
        'updated_at' => null,
      ],
      253 => [
        'id' => 254,
        'name' => 'Vaku',
        'created_at' => null,
        'updated_at' => null,
      ],
      254 => [
        'id' => 255,
        'name' => 'Vanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      255 => [
        'id' => 256,
        'name' => 'Vanga Kete',
        'created_at' => null,
        'updated_at' => null,
      ],
      256 => [
        'id' => 257,
        'name' => 'Vuhovi',
        'created_at' => null,
        'updated_at' => null,
      ],
      257 => [
        'id' => 258,
        'name' => 'Walungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      258 => [
        'id' => 259,
        'name' => 'Wamba',
        'created_at' => null,
        'updated_at' => null,
      ],
      259 => [
        'id' => 260,
        'name' => 'Wangata',
        'created_at' => null,
        'updated_at' => null,
      ],
      260 => [
        'id' => 261,
        'name' => 'Wanierukula',
        'created_at' => null,
        'updated_at' => null,
      ],
      261 => [
        'id' => 262,
        'name' => 'Watsa',
        'created_at' => null,
        'updated_at' => null,
      ],
      262 => [
        'id' => 263,
        'name' => 'Yabaondo',
        'created_at' => null,
        'updated_at' => null,
      ],
      263 => [
        'id' => 264,
        'name' => 'Yahuma',
        'created_at' => null,
        'updated_at' => null,
      ],
      264 => [
        'id' => 265,
        'name' => 'Yakusu',
        'created_at' => null,
        'updated_at' => null,
      ],
      265 => [
        'id' => 266,
        'name' => 'Yambuku',
        'created_at' => null,
        'updated_at' => null,
      ],
      266 => [
        'id' => 267,
        'name' => 'Yangala',
        'created_at' => null,
        'updated_at' => null,
      ],
      267 => [
        'id' => 268,
        'name' => 'Zongo',
        'created_at' => null,
        'updated_at' => null,
      ],
      268 => [
        'id' => 269,
        'name' => 'Aru',
        'created_at' => null,
        'updated_at' => null,
      ],
      269 => [
        'id' => 270,
        'name' => 'Boende',
        'created_at' => null,
        'updated_at' => null,
      ],
      270 => [
        'id' => 271,
        'name' => 'Bondo',
        'created_at' => null,
        'updated_at' => null,
      ],
      271 => [
        'id' => 272,
        'name' => 'Bongandanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      272 => [
        'id' => 273,
        'name' => 'Dungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      273 => [
        'id' => 274,
        'name' => 'Feshi',
        'created_at' => null,
        'updated_at' => null,
      ],
      274 => [
        'id' => 275,
        'name' => 'Gungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      275 => [
        'id' => 276,
        'name' => 'Kafakumba',
        'created_at' => null,
        'updated_at' => null,
      ],
      276 => [
        'id' => 277,
        'name' => 'Kongolo',
        'created_at' => null,
        'updated_at' => null,
      ],
      277 => [
        'id' => 278,
        'name' => 'Kunda',
        'created_at' => null,
        'updated_at' => null,
      ],
      278 => [
        'id' => 279,
        'name' => 'Likati',
        'created_at' => null,
        'updated_at' => null,
      ],
      279 => [
        'id' => 280,
        'name' => 'Lolo',
        'created_at' => null,
        'updated_at' => null,
      ],
      280 => [
        'id' => 281,
        'name' => 'Lubao',
        'created_at' => null,
        'updated_at' => null,
      ],
      281 => [
        'id' => 282,
        'name' => 'Mangala',
        'created_at' => null,
        'updated_at' => null,
      ],
      282 => [
        'id' => 283,
        'name' => 'Manono',
        'created_at' => null,
        'updated_at' => null,
      ],
      283 => [
        'id' => 284,
        'name' => 'Moba',
        'created_at' => null,
        'updated_at' => null,
      ],
      284 => [
        'id' => 285,
        'name' => 'Mufunga Sampwe',
        'created_at' => null,
        'updated_at' => null,
      ],
      285 => [
        'id' => 286,
        'name' => 'Ototo',
        'created_at' => null,
        'updated_at' => null,
      ],
      286 => [
        'id' => 287,
        'name' => 'Punia',
        'created_at' => null,
        'updated_at' => null,
      ],
      287 => [
        'id' => 288,
        'name' => 'Tshofa',
        'created_at' => null,
        'updated_at' => null,
      ],
      288 => [
        'id' => 289,
        'name' => 'Yaleko',
        'created_at' => null,
        'updated_at' => null,
      ],
      289 => [
        'id' => 290,
        'name' => 'Kasongo Lunda',
        'created_at' => null,
        'updated_at' => null,
      ],
      290 => [
        'id' => 291,
        'name' => 'Kabalo',
        'created_at' => null,
        'updated_at' => null,
      ],
      291 => [
        'id' => 292,
        'name' => 'Lomela',
        'created_at' => null,
        'updated_at' => null,
      ],
      292 => [
        'id' => 293,
        'name' => 'Yamongili',
        'created_at' => null,
        'updated_at' => null,
      ],
      293 => [
        'id' => 294,
        'name' => 'Minga',
        'created_at' => null,
        'updated_at' => null,
      ],
      294 => [
        'id' => 295,
        'name' => 'Tshumbe',
        'created_at' => null,
        'updated_at' => null,
      ],
      295 => [
        'id' => 296,
        'name' => 'Kapanga',
        'created_at' => null,
        'updated_at' => null,
      ],
      296 => [
        'id' => 297,
        'name' => 'Dikungu',
        'created_at' => null,
        'updated_at' => null,
      ],
      297 => [
        'id' => 298,
        'name' => 'Wembo Nyama',
        'created_at' => null,
        'updated_at' => null,
      ],
      298 => [
        'id' => 299,
        'name' => 'Mikope',
        'created_at' => null,
        'updated_at' => null,
      ],
      299 => [
        'id' => 300,
        'name' => 'Banga Lubaka',
        'created_at' => null,
        'updated_at' => null,
      ],
      300 => [
        'id' => 301,
        'name' => 'Lubutu',
        'created_at' => null,
        'updated_at' => null,
      ],
      301 => [
        'id' => 302,
        'name' => 'Kalonda Est',
        'created_at' => null,
        'updated_at' => null,
      ],
      302 => [
        'id' => 303,
        'name' => 'Kitutu',
        'created_at' => null,
        'updated_at' => null,
      ],
      303 => [
        'id' => 304,
        'name' => 'Bangabola',
        'created_at' => null,
        'updated_at' => null,
      ],
      304 => [
        'id' => 305,
        'name' => 'Kinkondja',
        'created_at' => null,
        'updated_at' => null,
      ],
    ]);
  }
}
