<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HealthZoneHealthZonesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        DB::table('health_zones')->truncate();

        DB::table('health_zones')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'Gombe',
                'latitude' => '-4.3095347',
                'longitude' => '15.2926308',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:43:24',
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Binza Ozone',
                'latitude' => '-4.348020429382444',
                'longitude' => '15.242345222290048',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:54:44',
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Limete',
                'latitude' => '-4.350633999999999',
                'longitude' => '15.348246',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:55:17',
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'Kokolo (Ndolo)',
                'latitude' => '-4.3199632',
                'longitude' => '15.3292177',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:57:36',
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'Binza Méteo',
                'latitude' => '-4.36161',
                'longitude' => '15.2384967',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:58:01',
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'Lemba',
                'latitude' => '-4.396010699999999',
                'longitude' => '15.3189726',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:58:32',
            ),
            6 =>
            array(
                'id' => 7,
                'name' => 'Kalamu 1',
                'latitude' => '-4.3488157',
                'longitude' => '15.3160455',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 11:59:59',
            ),
            7 =>
            array(
                'id' => 8,
                'name' => 'Lingwala',
                'latitude' => '-4.319352999999999',
                'longitude' => '15.2984842',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:00:33',
            ),
            8 =>
            array(
                'id' => 9,
                'name' => 'Kintambo',
                'latitude' => '-4.343598',
                'longitude' => '15.26775619999999',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:00:58',
            ),
            9 =>
            array(
                'id' => 10,
                'name' => 'Matete',
                'latitude' => '-4.3878727',
                'longitude' => '15.3511736',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:01:24',
            ),
            10 =>
            array(
                'id' => 11,
                'name' => 'Kingabwa',
                'latitude' => '-4.331000400000001',
                'longitude' => '15.3439173',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:01:50',
            ),
            11 =>
            array(
                'id' => 12,
                'name' => 'Kasa-vubu',
                'latitude' => '-4.344086000000001',
                'longitude' => '15.3043378',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:02:18',
            ),
            12 =>
            array(
                'id' => 13,
                'name' => 'Kinshasa',
                'latitude' => '-4.323859884239902',
                'longitude' => '15.308840078466796',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:03:28',
            ),
            13 =>
            array(
                'id' => 14,
                'name' => 'Bandalungwa',
                'latitude' => '-4.3394767',
                'longitude' => '15.2867776',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:03:56',
            ),
            14 =>
            array(
                'id' => 15,
                'name' => 'Barumbu',
                'latitude' => '-4.318751100000001',
                'longitude' => '15.3277541',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:04:23',
            ),
            15 =>
            array(
                'id' => 16,
                'name' => 'N\'sele',
                'latitude' => '-4.942558399999999',
                'longitude' => '15.6512395',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:07:58',
            ),
            16 =>
            array(
                'id' => 17,
                'name' => 'Selembao',
                'latitude' => '-4.3842422',
                'longitude' => '15.2867776',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:09:44',
            ),
            17 =>
            array(
                'id' => 18,
                'name' => 'Bumbu',
                'latitude' => '-4.374169300000001',
                'longitude' => '15.2926308',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:11:29',
            ),
            18 =>
            array(
                'id' => 19,
                'name' => 'Ngiri-Ngiri',
                'latitude' => '-4.359125100000001',
                'longitude' => '15.2984842',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:11:59',
            ),
            19 =>
            array(
                'id' => 20,
                'name' => 'Mont-Ngafula 1',
                'latitude' => '-4.4263717',
                'longitude' => '15.2955575',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:14:56',
            ),
            20 =>
            array(
                'id' => 21,
                'name' => 'Mont-Ngafula 2',
                'latitude' => '-4.353996366111101',
                'longitude' => '15.20167367339813',
                'created_at' => NULL,
                'updated_at' => '2020-06-19 12:45:21',
            ),
            21 =>
            array(
                'id' => 22,
                'name' => 'Kalamu 2',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array(
                'id' => 23,
                'name' => 'Masina 1',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array(
                'id' => 24,
                'name' => 'Kikimi',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array(
                'id' => 25,
                'name' => 'Maluku 1',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array(
                'id' => 26,
                'name' => 'N\'djili',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array(
                'id' => 27,
                'name' => 'Makala',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array(
                'id' => 28,
                'name' => 'Ngaba',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array(
                'id' => 29,
                'name' => 'Masina 2',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array(
                'id' => 30,
                'name' => 'Kisenso',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array(
                'id' => 31,
                'name' => 'Kimbanseke',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array(
                'id' => 32,
                'name' => 'Zone indeterminée',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array(
                'id' => 33,
                'name' => 'Goma',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array(
                'id' => 34,
                'name' => 'Beni',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array(
                'id' => 35,
                'name' => 'Butembo',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array(
                'id' => 36,
                'name' => 'Ibanda',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array(
                'id' => 37,
                'name' => 'Nyankunde',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array(
                'id' => 38,
                'name' => 'Bunia',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array(
                'id' => 39,
                'name' => 'Idiofa',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array(
                'id' => 40,
                'name' => 'Kenya',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array(
                'id' => 41,
                'name' => 'Tshamilemba',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array(
                'id' => 42,
                'name' => 'Kasumbalesa',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array(
                'id' => 43,
                'name' => 'Matadi',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array(
                'id' => 44,
                'name' => 'Nzanza',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array(
                'id' => 45,
                'name' => 'Bukavu',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            [
                'id' => 46,
                'name'=>'Police',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 47,
                'name'=>'Kingasani',
                'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 48,
            "name"=>'Kadutu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 49,
            "name"=>'Mvuzi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 50,
            "name"=>'Biyela',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 51,
            "name"=>'Karisimbi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 52,
            "name"=>'Himbi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 53,
            "name"=>'Lubumbashi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 54,
            "name"=>'Boma',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],[
                'id' => 55,
            "name"=>'Lukula',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 56,
            "name"=>'Mbanza Ngungu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 57,
            "name"=>'Nyirangongo',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 58,
            "name"=>'Rutshuru',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 59,
            "name"=>'Rutshuru',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 60,
            "name"=>'Kasindi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 61,
            "name"=>'Bonga Yasa',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 62,
            "name"=>'Kampamba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 63,
            "name"=>'Katuba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 64,
            "name"=>'Rwashi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 65,
            "name"=>'Kenge',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 66,
            "name"=>'Kabare',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 67,
            "name"=>'Malemba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 68,
            "name"=>'Makiso',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 69,
            "name"=>'Kimpese',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 70,
            "name"=>'Muanda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 71,
            "name"=>'Sekebanza',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 72,
            "name"=>'Mutuanga',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 73,
            "name"=>'Nyatende',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 74,
            "name"=>'Panzi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 75,
            "name"=>'Bagira',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 76,
            "name"=>'Wangata',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 77,
            "name"=>'Sonabata',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 78,
            "name"=>'Mumbanda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 79,
            "name"=>'Lukala',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 80,
            "name"=>'Masa',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 81,
            "name"=>'Kapemba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 82,
            "name"=>'Nyantende',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 83,
            "name"=>'Mumbunda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 84,
            "name"=>'Kisanga',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 85,
            "name"=>'Kapemba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 86,
            "name"=>'Kisantu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 87,
            "name"=>'Kangu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 88,
            "name"=>'Kwilu Ngongo',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 89,
            "name"=>'Madula',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 90,
            "name"=>'Mumbonda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 91,
            "name"=>'Bandundu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 92,
            "name"=>'Kampemba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 93,
            "name"=>'Kamalondo',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 94,
            "name"=>'Kidishi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 95,
            "name"=>'Mumbunda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 96,
            "name"=>'Watsa',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 97,
            "name"=>'Likasi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 98,
            "name"=>'Panda',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 99,
            "name"=>'Boko Kivula',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 100,
            "name"=>'Buta',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 101,
            "name"=>'Kaditu',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 102,
            "name"=>'Miti Murhesa',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 103,
            "name"=>'Fungurume',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 104,
            "name"=>'Luozi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 105,
            "name"=>'Lualaba',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 106,
            "name"=>'Uvira',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 107,
            "name"=>'Gemena',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 108,
            "name"=>'Sakania',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 109,
            "name"=>'Walikale',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 110,
            "name"=>'Kabondo',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
            [
                'id' => 111,
            "name"=>'Fizi',
            'latitude' => NULL,
                'longitude' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ],
        ));
    }
}
